import { type WineProduct, wineProductSchema } from "../types/catalog";

const wineCatalogSource = [
	{
		id: "chateau-pichon-baron-2018",
		name: "Chateau Pichon Baron",
		type: "red",
		region: "Pauillac, Bordeaux",
		country: "France",
		year: 2018,
		price: 96,
		currency: "EUR",
		description:
			"A structured Pauillac with blackcurrant, graphite, and cedar aromas. Fine-grained tannins and a persistent finish.",
		tastingNotes:
			"Blackcurrant, graphite, cedar, tobacco leaf. Full body with firm tannins.",
		foodPairing: ["lamb", "beef", "aged cheeses"],
		occasion: ["special dinner", "cellaring", "gift"],
		qualityTier: "luxury",
		abv: 13.5,
		ageRestricted: true,
	},
	{
		id: "brunello-di-montalcino-riserva-2016",
		name: "Brunello di Montalcino Riserva",
		type: "red",
		region: "Tuscany",
		country: "Italy",
		year: 2016,
		price: 78,
		currency: "EUR",
		description:
			"Classic Sangiovese depth with dried cherry, leather, and spice. Balanced acidity and polished tannins for long aging.",
		tastingNotes: "Dried cherry, leather, tobacco, spice, earthy undertones.",
		foodPairing: ["braised meats", "pasta with ragu", "truffle dishes"],
		occasion: ["anniversary", "collection", "Italian dinner"],
		qualityTier: "premium",
		abv: 14.5,
		ageRestricted: true,
	},
	{
		id: "rioja-reserva-vina-alta-2019",
		name: "Rioja Reserva Vina Alta",
		type: "red",
		region: "Rioja",
		country: "Spain",
		year: 2019,
		price: 29,
		currency: "EUR",
		description:
			"Tempranillo-led blend offering red plum, vanilla, and toasted oak. Smooth texture with savory notes and fresh lift.",
		tastingNotes: "Red plum, vanilla, coconut, tobacco, toasted oak.",
		foodPairing: ["tapas", "grilled pork", "manchego cheese"],
		occasion: ["weekend dinner", "tapas night", "value buy"],
		qualityTier: "mid",
		abv: 13.5,
		ageRestricted: true,
	},
	{
		id: "riesling-kabinett-goldtropfchen-2022",
		name: "Riesling Kabinett Goldtropfchen",
		type: "white",
		region: "Mosel",
		country: "Germany",
		year: 2022,
		price: 24,
		currency: "EUR",
		description:
			"Delicate citrus and white peach with slate-driven minerality. Light body, vibrant acidity, and a clean, off-dry finish.",
		tastingNotes: "Citrus, white peach, green apple, slate minerality.",
		foodPairing: ["sushi", "spicy Thai", "goat cheese", "light salads"],
		occasion: ["summer afternoon", "aperitif", "picnic"],
		qualityTier: "mid",
		abv: 8.5,
		ageRestricted: true,
	},
	{
		id: "chablis-premier-cru-fourchaume-2021",
		name: "Chablis Premier Cru Fourchaume",
		type: "white",
		region: "Burgundy",
		country: "France",
		year: 2021,
		price: 46,
		currency: "EUR",
		description:
			"Linear Chardonnay with lemon zest, green apple, and flint. Crisp structure and saline tension through the finish.",
		tastingNotes:
			"Lemon zest, green apple, oyster shell, flint, white flowers.",
		foodPairing: ["oysters", "shellfish", "sushi", "goat cheese"],
		occasion: ["seafood dinner", "fine dining", "summer party"],
		qualityTier: "premium",
		abv: 12.5,
		ageRestricted: true,
	},
	{
		id: "cotes-de-provence-rose-2023",
		name: "Cotes de Provence Rose",
		type: "rose",
		region: "Provence",
		country: "France",
		year: 2023,
		price: 18,
		currency: "EUR",
		description:
			"Pale and refreshing with wild strawberry, grapefruit, and herbal notes. Dry palate and bright, seaside freshness.",
		tastingNotes: "Wild strawberry, grapefruit, lavender, melon, herbs.",
		foodPairing: ["salads", "grilled fish", "light pasta", "soft cheeses"],
		occasion: ["beach day", "brunch", "aperitif", "summer party"],
		qualityTier: "entry",
		abv: 12,
		ageRestricted: true,
	},
	{
		id: "champagne-brut-premier-cru-nv",
		name: "Champagne Brut Premier Cru",
		type: "sparkling",
		region: "Champagne",
		country: "France",
		year: 2020,
		price: 65,
		currency: "EUR",
		description:
			"Fine mousse with brioche, citrus peel, and orchard fruit. Elegant autolytic depth with energetic acidity.",
		tastingNotes: "Brioche, citrus peel, green apple, almond, chalk.",
		foodPairing: ["oysters", "caviar", "fried foods", "soft cheeses"],
		occasion: ["celebration", "wedding", "New Year's", "luxury gift"],
		qualityTier: "premium",
		abv: 12,
		ageRestricted: true,
	},
	{
		id: "franciacorta-saten-millesimato-2019",
		name: "Franciacorta Saten Millesimato",
		type: "sparkling",
		region: "Lombardy",
		country: "Italy",
		year: 2019,
		price: 54,
		currency: "EUR",
		description:
			"Silky traditional-method bubbles with white flowers, almond, and pear. Creamy texture and refined, dry finish.",
		tastingNotes: "White flowers, almond, pear, cream, brioche.",
		foodPairing: ["risotto", "seafood pasta", "sushi", "antipasti"],
		occasion: ["anniversary", "dinner party", "Italian celebration"],
		qualityTier: "premium",
		abv: 12.5,
		ageRestricted: true,
	},
] as const satisfies readonly WineProduct[];

export const wines = wineProductSchema.array().parse(wineCatalogSource);
