/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/_callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as CallbackCallbackRouteImport } from './routes/_callback/callback'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSigninRouteImport } from './routes/_app/signin'
import { Route as AppGuideRouteImport } from './routes/_app/guide'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppAuthProfileRouteImport } from './routes/_app/_auth/profile'
import { Route as AppAuthDashboardRouteImport } from './routes/_app/_auth/dashboard'
import { Route as AppAuthSendIndexRouteImport } from './routes/_app/_auth/send/index'
import { Route as AppAuthLoanIndexRouteImport } from './routes/_app/_auth/loan/index'
import { Route as AppAuthSendSuccessRouteImport } from './routes/_app/_auth/send/success'
import { Route as AppAuthSendConfirmRouteImport } from './routes/_app/_auth/send/confirm'
import { Route as AppAuthLoanSuccessRouteImport } from './routes/_app/_auth/loan/success'

const CallbackRoute = CallbackRouteImport.update({
  id: '/_callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CallbackCallbackRoute = CallbackCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => CallbackRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSigninRoute = AppSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthProfileRoute = AppAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardRoute = AppAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSendIndexRoute = AppAuthSendIndexRouteImport.update({
  id: '/send/',
  path: '/send/',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthLoanIndexRoute = AppAuthLoanIndexRouteImport.update({
  id: '/loan/',
  path: '/loan/',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSendSuccessRoute = AppAuthSendSuccessRouteImport.update({
  id: '/send/success',
  path: '/send/success',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSendConfirmRoute = AppAuthSendConfirmRouteImport.update({
  id: '/send/confirm',
  path: '/send/confirm',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthLoanSuccessRoute = AppAuthLoanSuccessRouteImport.update({
  id: '/loan/success',
  path: '/loan/success',
  getParentRoute: () => AppAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/guide': typeof AppGuideRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/callback': typeof CallbackCallbackRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/profile': typeof AppAuthProfileRoute
  '/loan/success': typeof AppAuthLoanSuccessRoute
  '/send/confirm': typeof AppAuthSendConfirmRoute
  '/send/success': typeof AppAuthSendSuccessRoute
  '/loan/': typeof AppAuthLoanIndexRoute
  '/send/': typeof AppAuthSendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/guide': typeof AppGuideRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/callback': typeof CallbackCallbackRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/profile': typeof AppAuthProfileRoute
  '/loan/success': typeof AppAuthLoanSuccessRoute
  '/send/confirm': typeof AppAuthSendConfirmRoute
  '/send/success': typeof AppAuthSendSuccessRoute
  '/loan': typeof AppAuthLoanIndexRoute
  '/send': typeof AppAuthSendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_callback': typeof CallbackRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/guide': typeof AppGuideRoute
  '/_app/signin': typeof AppSigninRoute
  '/_app/signup': typeof AppSignupRoute
  '/_callback/callback': typeof CallbackCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_auth/dashboard': typeof AppAuthDashboardRoute
  '/_app/_auth/profile': typeof AppAuthProfileRoute
  '/_app/_auth/loan/success': typeof AppAuthLoanSuccessRoute
  '/_app/_auth/send/confirm': typeof AppAuthSendConfirmRoute
  '/_app/_auth/send/success': typeof AppAuthSendSuccessRoute
  '/_app/_auth/loan/': typeof AppAuthLoanIndexRoute
  '/_app/_auth/send/': typeof AppAuthSendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/signin'
    | '/signup'
    | '/callback'
    | '/dashboard'
    | '/profile'
    | '/loan/success'
    | '/send/confirm'
    | '/send/success'
    | '/loan/'
    | '/send/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/signin'
    | '/signup'
    | '/callback'
    | '/dashboard'
    | '/profile'
    | '/loan/success'
    | '/send/confirm'
    | '/send/success'
    | '/loan'
    | '/send'
  id:
    | '__root__'
    | '/_app'
    | '/_callback'
    | '/_app/_auth'
    | '/_app/guide'
    | '/_app/signin'
    | '/_app/signup'
    | '/_callback/callback'
    | '/_app/'
    | '/_app/_auth/dashboard'
    | '/_app/_auth/profile'
    | '/_app/_auth/loan/success'
    | '/_app/_auth/send/confirm'
    | '/_app/_auth/send/success'
    | '/_app/_auth/loan/'
    | '/_app/_auth/send/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_callback': {
      id: '/_callback'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_callback/callback': {
      id: '/_callback/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackCallbackRouteImport
      parentRoute: typeof CallbackRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signin': {
      id: '/_app/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AppSigninRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide': {
      id: '/_app/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/profile': {
      id: '/_app/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthProfileRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/send/': {
      id: '/_app/_auth/send/'
      path: '/send'
      fullPath: '/send/'
      preLoaderRoute: typeof AppAuthSendIndexRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/loan/': {
      id: '/_app/_auth/loan/'
      path: '/loan'
      fullPath: '/loan/'
      preLoaderRoute: typeof AppAuthLoanIndexRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/send/success': {
      id: '/_app/_auth/send/success'
      path: '/send/success'
      fullPath: '/send/success'
      preLoaderRoute: typeof AppAuthSendSuccessRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/send/confirm': {
      id: '/_app/_auth/send/confirm'
      path: '/send/confirm'
      fullPath: '/send/confirm'
      preLoaderRoute: typeof AppAuthSendConfirmRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/loan/success': {
      id: '/_app/_auth/loan/success'
      path: '/loan/success'
      fullPath: '/loan/success'
      preLoaderRoute: typeof AppAuthLoanSuccessRouteImport
      parentRoute: typeof AppAuthRoute
    }
  }
}

interface AppAuthRouteChildren {
  AppAuthDashboardRoute: typeof AppAuthDashboardRoute
  AppAuthProfileRoute: typeof AppAuthProfileRoute
  AppAuthLoanSuccessRoute: typeof AppAuthLoanSuccessRoute
  AppAuthSendConfirmRoute: typeof AppAuthSendConfirmRoute
  AppAuthSendSuccessRoute: typeof AppAuthSendSuccessRoute
  AppAuthLoanIndexRoute: typeof AppAuthLoanIndexRoute
  AppAuthSendIndexRoute: typeof AppAuthSendIndexRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardRoute: AppAuthDashboardRoute,
  AppAuthProfileRoute: AppAuthProfileRoute,
  AppAuthLoanSuccessRoute: AppAuthLoanSuccessRoute,
  AppAuthSendConfirmRoute: AppAuthSendConfirmRoute,
  AppAuthSendSuccessRoute: AppAuthSendSuccessRoute,
  AppAuthLoanIndexRoute: AppAuthLoanIndexRoute,
  AppAuthSendIndexRoute: AppAuthSendIndexRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppGuideRoute: typeof AppGuideRoute
  AppSigninRoute: typeof AppSigninRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppGuideRoute: AppGuideRoute,
  AppSigninRoute: AppSigninRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CallbackRouteChildren {
  CallbackCallbackRoute: typeof CallbackCallbackRoute
}

const CallbackRouteChildren: CallbackRouteChildren = {
  CallbackCallbackRoute: CallbackCallbackRoute,
}

const CallbackRouteWithChildren = CallbackRoute._addFileChildren(
  CallbackRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
