/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSigninRouteImport } from './routes/_app/signin'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppAuthIdentityRouteImport } from './routes/_app/_auth/identity'
import { Route as AppAuthEventsRouteImport } from './routes/_app/_auth/events'
import { Route as AppAuthDashboardRouteImport } from './routes/_app/_auth/dashboard'
import { Route as AppAuthBookingsRouteImport } from './routes/_app/_auth/bookings'
import { Route as AppAuthAgentRouteImport } from './routes/_app/_auth/agent'
import { Route as AppAuthEventsEventIdRouteImport } from './routes/_app/_auth/events.$eventId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSigninRoute = AppSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthIdentityRoute = AppAuthIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthEventsRoute = AppAuthEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardRoute = AppAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthBookingsRoute = AppAuthBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthAgentRoute = AppAuthAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthEventsEventIdRoute = AppAuthEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppAuthEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/agent': typeof AppAuthAgentRoute
  '/bookings': typeof AppAuthBookingsRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/events': typeof AppAuthEventsRouteWithChildren
  '/identity': typeof AppAuthIdentityRoute
  '/events/$eventId': typeof AppAuthEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/agent': typeof AppAuthAgentRoute
  '/bookings': typeof AppAuthBookingsRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/events': typeof AppAuthEventsRouteWithChildren
  '/identity': typeof AppAuthIdentityRoute
  '/events/$eventId': typeof AppAuthEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/signin': typeof AppSigninRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_auth/agent': typeof AppAuthAgentRoute
  '/_app/_auth/bookings': typeof AppAuthBookingsRoute
  '/_app/_auth/dashboard': typeof AppAuthDashboardRoute
  '/_app/_auth/events': typeof AppAuthEventsRouteWithChildren
  '/_app/_auth/identity': typeof AppAuthIdentityRoute
  '/_app/_auth/events/$eventId': typeof AppAuthEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/agent'
    | '/bookings'
    | '/dashboard'
    | '/events'
    | '/identity'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/agent'
    | '/bookings'
    | '/dashboard'
    | '/events'
    | '/identity'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_auth'
    | '/_app/signin'
    | '/_app/signup'
    | '/_app/'
    | '/_app/_auth/agent'
    | '/_app/_auth/bookings'
    | '/_app/_auth/dashboard'
    | '/_app/_auth/events'
    | '/_app/_auth/identity'
    | '/_app/_auth/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signin': {
      id: '/_app/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AppSigninRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/identity': {
      id: '/_app/_auth/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AppAuthIdentityRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/events': {
      id: '/_app/_auth/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppAuthEventsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/bookings': {
      id: '/_app/_auth/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppAuthBookingsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/agent': {
      id: '/_app/_auth/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAuthAgentRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/events/$eventId': {
      id: '/_app/_auth/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppAuthEventsEventIdRouteImport
      parentRoute: typeof AppAuthEventsRoute
    }
  }
}

interface AppAuthEventsRouteChildren {
  AppAuthEventsEventIdRoute: typeof AppAuthEventsEventIdRoute
}

const AppAuthEventsRouteChildren: AppAuthEventsRouteChildren = {
  AppAuthEventsEventIdRoute: AppAuthEventsEventIdRoute,
}

const AppAuthEventsRouteWithChildren = AppAuthEventsRoute._addFileChildren(
  AppAuthEventsRouteChildren,
)

interface AppAuthRouteChildren {
  AppAuthAgentRoute: typeof AppAuthAgentRoute
  AppAuthBookingsRoute: typeof AppAuthBookingsRoute
  AppAuthDashboardRoute: typeof AppAuthDashboardRoute
  AppAuthEventsRoute: typeof AppAuthEventsRouteWithChildren
  AppAuthIdentityRoute: typeof AppAuthIdentityRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthAgentRoute: AppAuthAgentRoute,
  AppAuthBookingsRoute: AppAuthBookingsRoute,
  AppAuthDashboardRoute: AppAuthDashboardRoute,
  AppAuthEventsRoute: AppAuthEventsRouteWithChildren,
  AppAuthIdentityRoute: AppAuthIdentityRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppSigninRoute: typeof AppSigninRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppSigninRoute: AppSigninRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
